/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cospas_sarsat_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7e421e5550b94558c3916832beb6ec94)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cospas/cospas_sarsat_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <cospas_sarsat_decoder_pydoc.h>

void bind_cospas_sarsat_decoder(py::module& m)
{

    using cospas_sarsat_decoder = ::gr::cospas::cospas_sarsat_decoder;


    py::class_<cospas_sarsat_decoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<cospas_sarsat_decoder>>(
        m, "cospas_sarsat_decoder", D(cospas_sarsat_decoder))

        .def(py::init(&cospas_sarsat_decoder::make),
             py::arg("sample_rate") = 6400.F,
             py::arg("debug_mode") = false,
             D(cospas_sarsat_decoder, make))


        .def("is_synchronized",
             &cospas_sarsat_decoder::is_synchronized,
             D(cospas_sarsat_decoder, is_synchronized))


        .def("get_frames_decoded",
             &cospas_sarsat_decoder::get_frames_decoded,
             D(cospas_sarsat_decoder, get_frames_decoded))


        .def("get_sync_failures",
             &cospas_sarsat_decoder::get_sync_failures,
             D(cospas_sarsat_decoder, get_sync_failures))


        .def("set_debug_mode",
             &cospas_sarsat_decoder::set_debug_mode,
             py::arg("enable"),
             D(cospas_sarsat_decoder, set_debug_mode))


        .def("reset_statistics",
             &cospas_sarsat_decoder::reset_statistics,
             D(cospas_sarsat_decoder, reset_statistics))

        ;
}
